# @format

version: "3.8"

services:
  # >> This is the docker-compose file for Dgraph.
  dgraph_zero:
    image: dgraph/dgraph:latest
    volumes:
      - ./data/dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=dgraph_zero:5080
  dgraph_alpha:
    image: dgraph/dgraph:latest
    volumes:
      - ./data/dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=dgraph_alpha:7080 --zero=dgraph_zero:5080 --security whitelist=${DGRAPH_WHITELIST}
  dgraph_ratel:
    image: dgraph/ratel:latest
    ports:
      - 8000:8000

  # dgraph-standalone:
  #   image: dgraph/standalone:latest
  #   volumes:
  #     - ./data/dgraph:/dgraph
  #   ports:
  #     - 5089:5080
  #     - 6089:6080
  #     - 8089:8080
  #     - 9089:9080
  #     - 8009:8000
  #   command: dgraph zero & dgraph alpha

  # <<This is the docker-compose file for Dgraph.
